accounts/urls.py
from django.urls import path, include

app_name = "accounts"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("learning_logs.urls")),
    path("accounts/", include("accounts.urls")),
]

learning_logs/urls.py
from django.urls import path

from . import views

app_name = "learning_logs"
urlpatterns =[
    path("", views.index, name="index"),
    path("topics/", views.topics, name="topics"),
    path('topics/(<int:topic_id>)/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name = 'new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name = 'edit_entry'),
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
            verbose_name_plural = "entries"

    def __str__(self):
        return f"{self.text[:50]}..." if len(self.text) > 50 else self.text

learning_logs/forms.py
from django import forms
from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render

# Create your views here.

learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm,EntryForm
# Create your views here.

def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')

def topics(request):
    name = Topic.objects.order_by('date_added')
    content = {'topics': name}
    return render(request, 'learning_logs/topics.html', content)

def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    content = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', content)

def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
    contex = {'form': form}
    return render(request, 'learning_logs/new_topic.html',contex)

def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    contex = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', contex)

def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    contex = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', contex)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a>
    <a href="{% url 'learning_logs:topics' %}">Tematy</a>
      {% if user.is_authenticated %}
      Witaj, {{user.username}}
      {% else %}
      <a href="{% url 'accounts:login' %}">Zaloguj</a>
      {% endif %}
  </p>
{% block content %} {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href ="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>
<p>Edycja wpisu</p>
<form action = "{% url 'learning_logs:edit_entry' entry.id %}" method = "post">
  {% csrf_token %}
  {{ form.as_div }}
  <button name="submit">Edytuj wpis</button>
</form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p>Learning log pomaga w monitorowaniu postepow w nauce.</p>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}
{% block content %}
<p><a href ="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Dodaj nowy wpis</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
  {% csrf_token %}
  {{ form.as_div}}
  <button name="submit">Dodaj wpis</button>
</form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}
{% block content %}
<p>Dodaj nowy temat:</p>
<form action="{% url 'learning_logs:new_topic' %}" method='post'>
  {% csrf_token %}
  {{ form.as_div}}
  <button name="submit">Dodaj temat</button>
</form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}
{% block content %}
<p>Temat: {{ topic.text }}</p>
<p>Wpisy:</p>
<a href="{% url 'learning_logs:new_entry' topic.id %}">Dodaj wpis</a>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'d M Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
        <p>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edytuj wpis</a>
        </p>
    </li>
    {% empty %}
    <li>Nie ma jeszcze żadnego wpisu.</li>
    {% endfor %}
</ul>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}
{% block content %}
  <p>Tematy</p>
  <ul>
    {% for topic in topics %}
      <li><a href="{% url 'learning_logs:topic' topic.id %}">{{topic.text}}</a></li>
     {%empty%}
    <li>Nie zostal dodany jeszcze zaden temat</li>
    {% endfor %}
  </ul>
<a href="{% url 'learning_logs:new_topic' %}">Dodaj nowy temat</a>
{% endblock content %}
</body>
</html>